### ISSUE TITLE
Resource: Module 2 / Step Into

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#10]
When we start to write programs that call internal helper functions, it can be hard to visualize the order in which code gets executed. So far they've only seen programs that execute from top to bottom, line by line. So we need to help them understand that a function is a block of code that *would* be executed *if and when* it were to be invoked from somewhere else -- even if the invocation happens "after" the function definition, and potentially multiple times from various places. And also the fact that when the function finishes executing, we "jump back" to where we were when we called it. They won't formally learn about "the stack" until module 3 or 4. 

Let's paint this picture with a video in which we use the IDE Debugger to step through a simple program with a main function that calls a helper function (at least twice). 

When we arrive at the call, we should use the `step into` feature on the debugger.

They were already introduced to the debugger in Module 1 with [this video](https://www.youtube.com/watch?v=-G_klBQLgdc), but they probably haven't used the 'step into' button yet.

Put video link and very short intro blurb [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/resources/step-into)

**Comment by newjoiner** [comment]
@jesseilev This resource needs to be completed.

**Comment by digshake** [comment]
Done! I removed the step-into folder, as I didn't think we needed it. Link to the video is on the prep page.

**Comment by jesseilev** [comment]
Nice!

I'm getting an audio issue with the video though. super loud dude talking about something in the background lol

**Comment by digshake** [comment]
Really? My bad, I'll redo it real quick.

**Comment by digshake** [comment]
Fixed!

**Comment by jesseilev** [comment]
Awesome! The vid is great. We should do more! (not sure where)
