### ISSUE TITLE
Exercise: Module 4, class 2 prep / Structs

### ISSUE THREAD

**Issue by brianrchen** [Launch-Code/cs50x-live-2016#103]
Make an exercise that makes the student use structs

put the exercise [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module4/calendar/cs50/unit2-advanced-c/module4/materials/exercises)
edit the calendar [here](https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module4/calendar/cs50/unit2-advanced-c/module4/materials/class2-prep/README.md)

**Comment by jesseilev** [comment]
Give them code that assumes existence of a struct. Their job is to make the struct.

What the code does:

Get a bunch of names and heights (in inches)

You must be this tall to ride the roller coaster

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#49
