### ISSUE TITLE
Exercise: Module 4, class 2 prep / Hex Converter

### ISSUE THREAD

**Issue by brianrchen** [Launch-Code/cs50x-live-2016#104]
Make the student write a program that converts back and forth from hex numbers, to learn about hex

put the exercise [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module4/calendar/cs50/unit2-advanced-c/module4/materials/exercises)
edit the calendar [here](https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module4/calendar/cs50/unit2-advanced-c/module4/materials/class2-prep/README.md)

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#48
