### ISSUE TITLE
Studio: Module 4, class 2 / Ascii Art

### ISSUE THREAD

**Issue by brianrchen** [Launch-Code/cs50x-live-2016#105]
Have the student write a program that reads in a file encoded like this:

(int)(int)(char)

a bunch of those.  The two ints are (x,y) locations.

Have them create a 2d char array with the chars in their proper (x,y) locations, then write it out to a file.

put the studio [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module4/calendar/cs50/unit2-advanced-c/module4/materials/studios)
edit the class page [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module4/calendar/cs50/unit2-advanced-c/module4/materials/class2)

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#47
