### ISSUE TITLE
Organization: Decide about Wiki

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#106]
Some complications have arisen in regards to the Wiki. Gotta decide how to proceed.

Options:
* SED script
* pillage
* third-party location
    * another wiki
    * gitbook

**Comment by jesseilev** [comment]
The plan:

We will keep the wiki, and also copy the content into another folder at the root level of the repo. Any links should point to the folder. But we will keep all the same content available on the wiki so that if a student later wants to go back and find a cheatsheet or something, they don't have to go hunt for the link again. 

Tasks:
1. Create folder (Jesse)
2. copy content into folder (Janelle)
3. change all links to point to the folder version (Janelle)
4. Every time a hub city makes a fork, someone needs to manually pull in the wiki (Jesse)

**Comment by jesseilev** [comment]
I made a new branch called feature/wiki-folder.

In that branch, I made a new folder, [here](https://github.com/Launch-Code/cs50x-live-2016/blob/feature/wiki-folder/helpful-resources/README.md)

**Comment by newjoiner** [comment]
Quick question - which folder will the helpful resources folder be located in once it is merged with the master, so I know where to link to.

ie: tree/master/helpful-resources
