### ISSUE TITLE
Exercise: Module 2 / Can You Vote

### ISSUE THREAD

**Issue by newjoiner** [Launch-Code/cs50x-live-2016#110]
The canyouvote.c file link leads to a 404 error.

**Comment by newjoiner** [comment]
@jesseilev The link for canyouvote.c is broken. I found the file in `module2/materials/exercises/array-read` [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/exercises/array-read).  If this is the correct file, we can put it [here](https://github.com/Launch-Code/cs50x-live-2016/blob/master/calendar/cs50/unit1-fundamentals/module2/materials/exercises/array-read/canyouvote.c)

**Comment by jesseilev** [comment]
@newjoiner good catch, i think this got duplicated. There is another exercise folder now which has the instructions for "Can You Vote?".

But the link to that exercise (from the [prep page]()) seems to be working fine. Where was the broken link you found.

I'm going to delete that other `/array-read/` folder now

**Comment by newjoiner** [comment]
Sorry, it's on the actual exercise page [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/exercises/can-you-vote).

**Comment by jesseilev** [comment]
Gotcha. Fixed!
