### ISSUE TITLE
Organization: St Louis Dates

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#113]
Add hard dates to the calendar and module homepages of the [St Louis fork](https://github.com/digshake/cs50x-live-2016-stlouis)

**Comment by digshake** [comment]
I've done this for Modules 0-3. Leaving this issue open so that we remember to do this for the other modules once we finalize the schedule.

**Comment by jesseilev** [comment]
nice

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#45
