### ISSUE TITLE
Resource: All Modules / Source code

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#118]
I would like to include links to the actual source code from all the CS50 walkthroughs (like the "answers" to the pseudocode, where all the TODOs are filled in.)

CS50 hosts these files on their site. I started adding the links on the homepage for each module under a section titled "Helpful Links". For example, see [Module1](https://github.com/Launch-Code/cs50x-live-2016/tree/master/calendar/cs50/unit1-fundamentals/module1). 

But I think that was the wrong place to put these links-- they feel out of place there. They probably belong somewhere in the wiki (and helpful-resources folder), like, under a subfolder called `/source-code/`. Or maybe just somewhere on the markdown file for each module, e.g. `module1.md`

**Comment by newjoiner** [comment]
@jesseilev I put the files in helpful-resources [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/wiki-folder/helpful-resources/source-code). Every follow-along is listed along with links to that entire week's source code.  I also linked it on the helpful-resources homepage [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/wiki-folder/helpful-resources)

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#43
