### ISSUE TITLE
Exercise: Module 2 / atoi

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#12]
Come up with a super simple exercise that requires them to use the `atoi` function.

Put instructions in this [README](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/exercises/atoi)

**Comment by newjoiner** [comment]
@jesseilev This exercise needs a little fixing. 


```c
#include<cs50.h>
#include<stdio.h>

int main ()
{
    int i;
    string input;

    // Add a separate line - printf("Please enter a number: ")
    input = GetString("Please enter a number:");

    // Shouldn't they be printing i instead of input.
    // Add \n 
    printf ("The value entered is %d.", input);

    return 0;
}
```

**Comment by jesseilev** [comment]
Hmm yeah, might need a supplementary resource as well.

**Comment by jesseilev** [comment]
Done. Changed exercise name to Previous. 

<a href="https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/class2-prep/README.md#command-line-arguments" target="_blank">Link</a>
