### ISSUE TITLE
GH Pages: Style / Blank Table Cells

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#123]
The tables don't look right.

Possibly other little things?

**Comment by jesseilev** [comment]
solution: fork the couscous template and modify the css

**Comment by digshake** [comment]
Tables and bullets work, but blank table cells aren't displayed so I'm going to leave this issue open as a reminder to fix them.

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#42
