### ISSUE TITLE
GH Pages: Workflow / Jesse can't push

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#135]
@digshake 

I seem to have lost permission to push to the <a href="https://github.com/digshake/cs50x-live-2016-stlouis" target="_blank">st louis repo</a>:
```
$ git push origin 
remote: Permission to digshake/cs50x-live-2016-stlouis.git denied to jesseilev.
fatal: unable to access 'https://github.com/digshake/cs50x-live-2016-stlouis.git/': The requested URL returned error: 403
```

Any idea why?

Also, I just noticed that all our crazy feature branches are showing up on your fork. Did I cause that to happen just now?

This workflow is obviously still a little hairy currently. I'm going to try to hold of doing fork-related stuff till next time you're in the office.

**Comment by digshake** [comment]
You should be able to push now. I just forgot to add you as a collaborator when I reforked the repo yesterday.

As for the extra branches, that doesn't surprise me - you added those branches to the template repo after I forked it the first time, I believe. I don't think they are really hurting anything, but you can remove them if you want.

**Comment by jesseilev** [comment]
Sick
