### ISSUE TITLE
GH Pages: Organization / Domain Name

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#138]
Look into getting a nice domain name!

something like 
* launchcode.org/cs50x/stlouis
* cs50x.launchcode.org/stlouis
* launchcodecs50x.org/stlouis

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by jesseilev** [comment]
@terribleplan do you have any time to consult on this today?

**Comment by jesseilev** [comment]
It's probably going to be 

launchcodecs50x.org/stlouis

Unless one of these things happen:
* we decide we want to generalize beyond just cs50:
    * launchcodeclasses.org/cs50x/stlouis
* tech team decides they are ok with cs50x.launchcode.org/stlouis
    * seems nice because it's part our regular domain, but I don't feel strongly. Not worth causing unnecessary pain for the tech team
* someone has another idea or is against this one for another reason

**Comment by jesseilev** [comment]
Beyond just deciding about the name, we also realized that we might need to rethink our overall system for hub city repos.

It always seemed less than ideal to place the content on the individual profile of each hub city instructor. Not just because it looks weird (which can be hidden by changing the domain name), but also because it makes it harder to manage in general.
* The instructor needs to add us as contributors
* What if the instructor wants to hand it off to a new instructor?
* etc

It would be better to keep all the forks under a legit Organization profile. We thought this wasn't possible, because you can't fork your own repo. but Keegan points out there are ways to scheme around this:
* you can have someone else fork it, change the name, and then fork it back from them
* github support is apparently pretty accommodating towards organizations trying to do this type of thing

@terribleplan suggested we create a new Organization rather than use Launch-Code. I don't remember why... Is it because our domain will then be stuck with Launch-Code in the name?

**Comment by terribleplan** [comment]
@jesseilev The reason is that basically if you want to have sub pages that correspond to repos (such as `launchcodecs50x.org/st-louis`) you need to have a base repository for an organization called `<org-name>.github.io` with a `CNAME` file, and then have repositories called what the sub-pages are (`st-louis`).

Also, it would prevent LC from having our own github-hosted page if we ever wanted to do that as a tech team/organization.

**Comment by terribleplan** [comment]
(such as http://twitter.github.io/)

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#38
