### ISSUE TITLE
Exercise: Module 3, class 2 prep / Delmar House of Tires

### ISSUE THREAD

**Issue by newjoiner** [Launch-Code/cs50x-live-2016#139]
In the exercise instructions students are told to include the mathHelper.h file, but it is already in the file.  We can comment that out and put a Todo like in <a href="https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/exercises/spread-out/houseOfTires.c" target="_blank">houseOfTires.c</a>

_Instructions for Module 3_
3 Add a line to #include mathHelper.h in <a href="https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/exercises/spread-out/houseOfPizza.c" target="_blank">houseOfPizza.c</a>

This is the first exercise where students will be handling multiple files on their own.  It might be good to add some instructions for compiling as well. In Studio Multiplication and Exponents they are given a make file.

**Comment by newjoiner** [comment]
@jesseilev

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#37
