### ISSUE TITLE
Exercise: Module 2 / Census

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#14]
Come up with an exercise that requires them to "decompose" a cluttered program with a long main function by pulling out some piece of the work into a separate function (especially something that is done repeatedly).

Write instructions in this [README](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/exercises/census). Provide the source code of the "cluttered version" of the program in a separate .c file.

**Comment by digshake** [comment]
Perhaps I am thinking about this problem wrong, but I don't see a way to complete this exercise as designed without arrays. This is a problem since arrays aren't introduced until the following class.

**Comment by newjoiner** [comment]
@jesseilev The link to the cencus.c file is broken.  In the `module2/materials/exercises/decomposition` folder there is a cencus.c file. The file is incomplete, but if this is the right file we can move it [here](https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/exercises/census/census.c).

Also digshake commented above.

**Comment by jesseilev** [comment]
solution: move this to class 2 prep

**Comment by jesseilev** [comment]
Done
