### ISSUE TITLE
Studio: Module 3 / Multiplication and Exponents

### ISSUE THREAD

**Issue by newjoiner** [Launch-Code/cs50x-live-2016#141]
The instructions for [this](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/studios/multiplication-exponent) studio can be broken up into parts.

Check the wiki [here](https://github.com/Launch-Code/cs50x-live-2016/blob/feature/wiki-folder/helpful-resources/modules/module-3.md#class-2-studio-multiplication-and-exponents) to see it broken up.

**Comment by newjoiner** [comment]
forgot to mention @jesseilev

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#35
