### ISSUE TITLE
Organization: Module 3 / Merge Sort

### ISSUE THREAD

**Issue by newjoiner** [Launch-Code/cs50x-live-2016#142]
Might want to add Doug's Playlist to this section.  All of the other sorting algorithms have doug's playlist video.

You can find the video [here](https://www.youtube.com/watch?v=sWtYJv_YXbo&index=6&list=PLhQjrBD2T382Bh-sc1w74c4V6_G2byC-T) and put it in Module 3 Class 2 Prep [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/class2-prep#merge-sort)

**Comment by newjoiner** [comment]
forgot to mention @jesseilev

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#34
