### ISSUE TITLE
typo in Hello exercise

### ISSUE THREAD

**Issue by stlou** [Launch-Code/cs50x-live-2016#147]
at bottom of exercise, when you copy the hello.c file into pset1, you say to write:

``$ cp -r ~/workspace/module1/hello ~/workspace/pset1/hello``

however, it's in the exercises folder of module1. so, should write:

``$ cp -r ~/workspace/module1/exercises/hello ~/workspace/pset1/hello``

not sure if this was already pushed live or not...

**Comment by newjoiner** [comment]
@jesseilev I fixed the typo in hello and it has to be updated for St. Louis
