### ISSUE TITLE
typo in follow along pseudocode

### ISSUE THREAD

**Issue by stlou** [Launch-Code/cs50x-live-2016#148]
In all the pseudocodes for the follow alongs, we say to save in a folder "follow_alongs" as so:

``  * Save in Folder: ~/workspace/module1/follow_alongs/hello``

however, in the file management exercise, we labeled the folder as "followalongs". So, to be consistent, should change it all to:

``  * Save in Folder: ~/workspace/module1/followalongs/hello`` (or whatever the followalong should be)

**Comment by newjoiner** [comment]
@jesseilev I fixed the typos for Module 1 and Module 3.  They have to be updated in the St. Louis version.

**Comment by jesseilev** [comment]
awesome thanks @newjoiner
