### ISSUE TITLE
Studio: Module 3 / Class 2

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#21]
We need a studio for this class. Something that requires recursion and is *slightly* more difficult than the <a href="https://github.com/Launch-Code/cs50x-live-2016/tree/master/calendar/cs50/unit1-fundamentals/module3/materials/exercises/fibonacci">Fibonacci</a> exercise. 

In addition, we want to get them comfortable with programs composed of multiple files:
* mainthing.c
* helperstuff.h
* helperstuff.c

So try to come up with a scenario in which it makes sense for use multiple files like that. 

Put stuff <a href="https://github.com/Launch-Code/cs50x-live-2016/tree/master/calendar/cs50/unit1-fundamentals/module3/materials/studios/studio2" target="_blank">here</a>

**Comment by digshake** [comment]
I've committed a first draft of this called multiplication and exponents. I'd love it if someone would take a look and give me some feedback.

**Comment by digshake** [comment]
Gonna go ahead and close this one out. Feel free to reopen it if you see any problems with it.
