### ISSUE TITLE
Resource: Module 2 / Calling Functions

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#3]
Write a quick review of how to call a library function. Use `strlen` as example.

Talk about side effect vs return value. Mention `printf` as example of side effect.

Emphasize that you have to actually **use** the return value of the function by storing it in a variable or embedding the function call inside a larger expression, e.g. don't do this:

```
strlen("hello");
```

do this: 
```
int len = strlen("hello");
// and now use len in your code
```

put it in this [README](https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/resources/calling-functions/README.md)

**Comment by digshake** [comment]
I went through this exercise and cleaned up the wording a bit. Closing this issue for now.

**Comment by newjoiner** [comment]
@jesseilev In the Side Effects section of this resource it explains that the function returns 5 `strlen("hello")`, but in the code the variable `exampleString` is `"hello!"`. This would return 6.

We should also add `<string.h>`, so if the students want to use strlen, they know to use that library.

Also do we want to add syntax highlighting like below?

```c
#include <stdio.h>
#include <cs50.h>
#include <string.h>

int main(void)
{
    
    string exampleString = "hello!";

    // call strlen and store its return value in a variable
    int exampleStringLength = strlen(exampleString);

    printf("The string has %i characters!\n", exampleStringLength);
}
```

**Comment by jesseilev** [comment]
@newjoiner 

Great catch. I totally forgot about `<string.h>`. I am afraid there might be a couple more instances where we talk about `strlen` without mentioning it, so keep your eye out.

Yes, syntax highlighting is awesome. From now on I will add syntax highlighting to any code blocks I write, and if you happen to come across some colorless blocks, go ahead and fix them. (But don't worry about trying to track down every last one.)

In case anyone is wondering, the way to add syntax highlighting in markdown is to specify the language after your opening 3 back-ticks, like this:
*  \`\`\`c 
* \`\`\`javascript

**Comment by jesseilev** [comment]
I added `string.h` and syntax highlighting, and wrote some more text.
