### ISSUE TITLE
Studio: Module 4 / Word Grid Stretch (pointers and malloc)

### ISSUE THREAD

**Issue by brianrchen** [Launch-Code/cs50x-live-2016#33]
make a studio that forces the student(s) to use malloc and pointers

given a word, stretch it in 2d; desc already up in readme

put that studio [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module4/calendar/cs50/unit2-advanced-c/module4/materials/studios/word-grid-stretch)

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#59
