### ISSUE TITLE
Exercise: Module 2, class 1 prep / Typecasting

### ISSUE THREAD

**Issue by brianrchen** [Launch-Code/cs50x-live-2016#38]
"Read" and "Do" for typecasting still there; need to decide on whether to move these resource to module 1, then edit the calendar [here](https://github.com/Launch-Code/cs50x-live-2016/blob/master/calendar/cs50/unit1-fundamentals/module2/materials/class1-prep/README.md).

**Comment by newjoiner** [comment]
@jesseilev This exercise still needs to be completed.

**Comment by jesseilev** [comment]
I have taken it out of the prep now.
