### ISSUE TITLE
Organization: Module 2, exercises

### ISSUE THREAD

**Issue by brianrchen** [Launch-Code/cs50x-live-2016#42]
fill out a list of exercises/links to exercises in [Module 2: exercises](https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/exercises/README.md)

**Comment by jesseilev** [comment]
Let's not have these README pages at the `/exercises/` root. Most students will never arrive at this location anyway.

 I've deleted the module1 one already. Will do the same for m2 and any others that have it.
