### ISSUE TITLE
Resource: Module 2 / Magic Numbers

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#6]
Write a little example program that illustrates using global constants to pull magic numbers out of your code.

Write 2 .c files, the "before" version and the "after" version.

Place them in this [directory](https://github.com/Launch-Code/cs50x-live-2016/tree/master/calendar/cs50/unit1-fundamentals/module2/materials/resources/magic-numbers)

**Comment by digshake** [comment]
Filled in the TODO, and fixed a very small bug in the code.
