### ISSUE TITLE
Organization: Module 1 / Exercise Instructions

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#78]
In [Haiku](https://github.com/Launch-Code/cs50x-live-2016/blob/master/calendar/cs50/unit1-fundamentals/module1/materials/exercises/haiku/README.md) we need to give them very explicit instructions on how to open up the IDE and make some folders and yada yada. Make sure to link them to The wiki page on IDE folder structure.

**Comment by newjoiner** [comment]
Hey Jesse, I am adding some links in Module 1 and I think it would be better to include an exercise in Module 1 Prep for Class 1 that has the students set up all of the folders.  This Exercise can be the first task they complete in the Printing, Getting User Input section (before their first follow along) or it can come after Doug's Playlist Command Line in the Getting Set up section.

I am emailing you a copy of the exercise as well and you can make the final changes if you think this is a good idea.

IE:

File Management

Now that you have written your first program in the CS50 IDE, you will create some directories (folders) to place the programs in, that you will be developing throughout the course.  For this exercise you will create all of the directories now, so you do not have to do it for each module.

Please Read the File Management Resource <a href="https://github.com/Launch-Code/cs50x-live-2016/wiki/File-Management-Resource" target="_blank">here</a> first, for an explanation, and then follow the directions below.

1. You will create a directory (folder) for Module 1 in the **`~/workspace/`** directory. 
  * Use the command **`mkdir module1`**  in the terminal window. (_**Make sure you are in your home folder**_ **`~/workspace/`** or in some cases **`~/ide50/`**)
2. Go to the module1 directory you just created using the command **`cd module1`**.  (You should already be in your home directory.)
3. You will make 4 more directories in the module1 directory.  
  * **`mkdir exercises`**
  * **`mkdir followalongs`**
  * **`mkdir misc`**
  * **`mkdir studios`**
4. Go back to the home directory. (You can use the command **`cd ..`** to go get to each parent directory.) You will repeat this process for the rest of the modules. You only have to change the module name (IE: module2, module3, etc.) The subfolders (exercises, followalongs, misc, and studios) will remain the same for each module.

*You can also use the CS50 graphical display to create these directories by right-clicking on the workspace or ide50 folder, selecting New Folder, and then rename the folder to module1. You would repeat this process for the subfolders, but would right-click the module1 folder instead.

:smiley: Woohoo!! Thought you were done, didn't you!! 

We also have to make some folders for your Problem Sets!!  :smiling_imp: 

You will make 8 directories in your home folder (**`~/workspace/`** or **`~/ide50/`** in some cases) named pset1 .... pset8.  You can use the command **`mkdir pset1`** and repeat the process for all 8 problem sets. Make sure that all of the pset folders are located in the **`~/workspace/`** or **`~/ide50/`** in some cases, folder.

**Comment by jesseilev** [comment]
Hey Janelle,

This looks good. 

I previously put something similar in [Haiku](https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module1/calendar/cs50/unit1-fundamentals/module1/materials/exercises/haiku/README.md).

Feel free to synthesize my version and yours as you see fit. 

As far as whether it should be part of Haiku or pulled out as a separate exercise, I could go either way. If you think a separate exercise is better, go for it. 

Also, this reminds me that I changed my mind about one aspect of the folder structure: I want them to make a new directory for each individual exercise (or studio):
```
|---- /exercises
      |---- /haiku
            |---- haiku.c
      |----- /book
            |---- book.c
      |----- /larger_thing
            |---- largerthing.c
            |---- helper.h
            |---- helper.c
...
|---- /studios
      |---- /donuts
            |---- donuts.c
...
```

Follow-Alongs can be grouped together by project, since there are often iterated versions of the same project:
|---- /followalongs
      |---- /adder
            |---- adder.c
      |---- /student
            |---- student-0.c
            |---- student-1.c
            |---- student-2.c
...

Can you edit the Folder Structure Wiki page  to reflect that change?

**Comment by jesseilev** [comment]
Another idea just occurred to me:

I always disliked how the first thing we do is send them to Problem Set 1 to set up their IDE and do that Hello World exercise; sending them over to a Pset during prep is not something we normally do and I imagine it will be a somewhat confusing experience.

Maybe we should just make our own Hello exercise, which can copy much of the Pset1 text where appropriate, but also includes our own instructions about creating the directories.

**Comment by newjoiner** [comment]
Hi Jesse,

I created a Hello exercise, (I'll send via email) that adheres to the file structure that we've discussed.  
When creating the Hello exercise, it was pretty long as is, so I copied your instructions from the Haiku exercise and put it in the File Management Resource. It now has a Setting up the Directory section.  Maybe it can follow this order so that they are concentrating on one topic for each task.

|  Task | Resource Type | Link | Instructions |
|  :----:  | :-----: | :-----:  | :-----------: |
|Set up your IDE | Problem Set | CS50 IDE |  |
|Set up your Directory | Exercise | File Management Resource |  |
|Hello World! | Problem Set | Hello |  Write your first program |

**Comment by jesseilev** [comment]
Done!
