### ISSUE TITLE
Organization: Git Workflow

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#84]
We're going to set up a proper git workflow so that as we complete new content, we can smoothly roll it out to the public.

This will involve creating some branches:
* `master` is the "official" version that students will look at. So by the end of this week, `master` will contain Module 0 only, and the rest, because they are currently incomplete, will be totally gone with a "Coming Soon!" message
* `develop` is more or less the same as `master`, but provides a staging ground where we can QA any changes before merging them into `master`
* For each little unit of additional content, we'll make a separate branch. For example:
  * `feature/module4` will contain Module 0 and Module 4
  * `feature/module7` will contain Module 0 and Module 7 

The instructor for each hub city (currently that's just @digshake in St Louis) will make a fork of our `master`, and can then fetch the upstream changes as they come in. The hairiness of us adding new features will be hidden from them so they don't get slammed with terrible merge conflicts.

**Comment by digshake** [comment]
Since this has been finished (and it works great!), I'm going to go ahead and close this issue.
