### ISSUE TITLE
Organization: Exercise "Back" buttons

### ISSUE THREAD

**Issue by stlou** [Launch-Code/cs50x-live-2016#85]
When you go to an Exercise, you stay in the same window (we like that, since you're staying internal within the curriculum / website). 

BUT, when you click the back button ("Go back to Prep for Class #"), it takes you back to the top of the Prep Work page. This ends up being a little annoying, since you constantly have to scroll down to find where you left off.

We can make those "Back" buttons link to the header for the section the exercise is in. We should do that. Students will appreciate it (even if they don't know that it could be worse, they'll know).

**Comment by jesseilev** [comment]
What's the status of this?

**Comment by newjoiner** [comment]
Hey @jesseilev I can take care of these

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#56
