### ISSUE TITLE
Exercise: Module 7, class 1 prep / php sessions

### ISSUE THREAD

**Issue by brianrchen** [Launch-Code/cs50x-live-2016#91]
make the student use php session variables

edit the calendar [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module7/calendar/cs50/unit3-web/module7/materials/class1-prep/README.md)
put the exercise [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module7/calendar/cs50/unit3-web/module7/materials/exercises)

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#62
