### ISSUE TITLE
Follow Along: Module 3, class 2 prep / sigma-0, sigma-1

### ISSUE THREAD

**Issue by newjoiner** [Launch-Code/cs50x-live-2016#98]
Currently these follow alongs are listed as:

| Task | Resource Type | Link | Instructions |
| :-----: | :-----: | :-----: | :-----: | 
| Follow Along | Resource | Walkthrough: sigma-0 | |
| Follow Along | Resource | Walkthrough: sigma-1 | |

Change for consistency:

| Task | Resource Type | Link | Instructions |
| :-----: | :-----: | :-----: | :-----: | 
| Follow Along | Walkthrough | sigma-0 | |
| Follow Along | Walkthrough | sigma-1 | |

**Comment by digshake** [comment]
Done!
