### ISSUE TITLE
Resource: Module 4, class 1 prep / Why Pointers

### ISSUE THREAD

**Issue by brianrchen** [Launch-Code/cs50x-live-2016#99]
Write a resource with an example of why pointers are useful, explaining why they solve our problems implementing "swap" and "compare"

put the resource [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module4/calendar/cs50/unit2-advanced-c/module4/materials/supplementary-resources)
edit the calendar [here](https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module4/calendar/cs50/unit2-advanced-c/module4/materials/class1-prep/README.md)

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#50

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#52
